### ISSUE TITLE
Minimum Android API requirement

### ISSUE THREAD

**Issue by berkedel** [Lenddo/android-lenddo-data#13]
Currently the minimum version is 16. Can I use this SDK with android API 15?

**Comment by Howard3** [comment]
Hello Berkedel, 

Currently we don't support Android api level 15. We find that it is less than 1% market share, as such it has not been a priority. What percentage of your target user base are using this version of Android? 

Best Regards, 
Howard

**Comment by jom16antonio** [comment]
No more feedback. Closing this issue.
