### ISSUE TITLE
Import module rename app

### ISSUE THREAD

**Issue by felixeduardo15** [Lenddo/android-lenddo-data#15]
After you have finished running the application, the name of this changes to "LenddoData", is there any way to prevent this?

Using the instructions [LenddoData] (https://github.com/Lenddo/android-lenddo-data/releases/tag/v2.20.2).

**Comment by Howard3** [comment]
Hello felix, 

What is being renamed? 

Best Regards, 
Howard

**Comment by felixeduardo15** [comment]
Rename the APK to LenddoData

**Comment by jom16antonio** [comment]
Hi @felixeduardo15,

It seems the app_name variable of your app is not set properly or is being overwritten by the app_name set in the datasdk library.
Another fix is, in the lenddodatasdk module, under values and values-es resource directories, modify the strings.xml app_name variable to reflect the name of your application.

```xml
<resources>
    <string name="app_name">LenddoData</string>
```

Regards,
Joey
